### ISSUE TITLE
qBittorrent和qBittorrent-ClientBlocker同时启动问题

### ISSUE THREAD

**Issue by Grox9426** [Simple-Tracker/qBittorrent-ClientBlocker#105]
Windows客户端（本机）的qBittorrent在启动时会因做种数过多会加载一段时间Torrent
![QQ截图20240807102157](https://github.com/user-attachments/assets/2d6169d1-2e47-4b23-936f-78808998806f)

如果qBittorrent-ClientBlocker在Torrent加载完成前启动会发生错误并自动退出
![f9123ab0-f15a-4fac-82db-7ee831d32c3e](https://github.com/user-attachments/assets/48a102fd-0180-4d0b-8c59-571c23df5af5)

我的需求和解决方法（临时）：

我因个人需求通过下面这个bat脚本来一键启动qBittorrent和qBittorrent-ClientBlocker
![QQ截图20240807102517](https://github.com/user-attachments/assets/e5ce73c8-cef9-4fdf-9a43-e2af797d66dd)

我暂时的解决方法是通过增加 `timeout` 的时间来达到qBittorrent-ClientBlocker在qBittorrent加载完成Torrent后启动，但估计后续随着做种数越来越多而频繁更改这个 `timeout` 的时间

希望可以有方法能让qBittorrent-ClientBlocker判断qBittorrent当前是否完成启动，或者发生类似错误时可以重试而不是直接退出

**Comment by Simple-Tracker** [comment]
感谢反馈!

目前, 可以通过参数 ```--startdelay``` 设置启动延迟. 未来, 可能会加入不退出的选项.

**Comment by Simple-Tracker** [comment]
3.5b2 已发布, 配置文件新设置项 IgnoreFailureExit 可以使首次检测客户端或认证失败后不再退出, 而是反复重试.
