### ISSUE TITLE
新的伪装客户端：Gopeed dev

### ISSUE THREAD

**Issue by LMDM387** [Simple-Tracker/qBittorrent-ClientBlocker#106]
目前PeerID使用的是随机码，没发现常用的IP段
客户端名称为：Gopeed dev
使用地址：61.147.234.2/218.90.201.2目前不在BTN-Collected-Rules里
![QQ图片20240807215011](https://github.com/user-attachments/assets/557c3938-605c-4cae-bf05-3f624aa3e60f)

**Comment by IAALAI** [comment]
我还想着，干脆直接的封禁全部的dev好了的说。。。

**Comment by LMDM387** [comment]
直接全杀容易误伤吧，虽然会标dev的基本都是坏东西
暂且还是一个个的杀

**Comment by HaoTian22** [comment]
今天（UTC+8）1点同样看见这两个IP在疯狂下载

**Comment by Simple-Tracker** [comment]
感谢反馈!

已更新 config.json, IP 相关信息等待依赖项目跟进.

**Comment by maidmeow4** [comment]
已观察到，PeerID随机，进度一直为零

**Comment by liuzhaoze** [comment]
已观察到

![QQ截图20240816001904](https://github.com/user-attachments/assets/7cab6bbd-8836-4d44-80ca-6de3a5d8dd77)

**Comment by IAALAI** [comment]
> 直接全杀容易误伤吧，虽然会标dev的基本都是坏东西 暂且还是一个个的杀

不会的这个狗屁下载器就不是好东西，本身就没有上传的逻辑

**Comment by LMDM387** [comment]
> > 直接全杀容易误伤吧，虽然会标dev的基本都是坏东西 暂且还是一个个的杀
> 
> 不会的这个狗屁下载器就不是好东西，本身就没有上传的逻辑

那直接杀就完事，砍爆.jpg
不过我个人依然不是很推荐直接用正则全杀，看到一个加一个就算了

**Comment by luozi3** [comment]
![图片](https://github.com/user-attachments/assets/9d55b4ff-dca3-448f-ba91-2eb83671b869)
比特彗星结果

**Comment by luozi3** [comment]
如何直接封dev客户端啊？最近一直在吸血，屏蔽无效，bitcomet显示无效的ip地址
我是小白，有点迷惑。
112.23.146.2
112.21.127.2

**Comment by luozi3** [comment]
![图片](https://github.com/user-attachments/assets/0a35c014-61e7-43ab-a089-fe03e70da723)

**Comment by LMDM387** [comment]
> 如何直接封dev客户端啊？最近一直在吸血，屏蔽无效，bitcomet显示无效的ip地址 我是小白，有点迷惑。 112.23.146.2 112.21.127.2

blockList下添加一行
"^-dev"
就行了
这是通配符，任意带dev的客户端都杀杀杀杀
如果该行不是最后一行，那就再加上一个英文逗号

**Comment by maidmeow4** [comment]
> 如何直接封dev客户端啊？最近一直在吸血，屏蔽无效，bitcomet显示无效的ip地址 我是小白，有点迷惑。 112.23.146.2 112.21.127.2

@liuzhaoze 你可以试试在 **选项 -> BT下载 -> 允许连接的BT客户端列表** 里边把 **Other clients** 取消勾选
