### ISSUE TITLE
吸血客户端 前引号加 _ 下划线

### ISSUE THREAD

**Issue by tanmoumou252** [Simple-Tracker/qBittorrent-ClientBlocker#108]
ip : 119.188.233.101
 客户端为 一个`引号加 _`  而且这个`引号`和`_`还是上下重叠起来的
 
 目前它在下载恶魔的破坏
 ```
 https://mikanime.tv/RSS/Bangumi?bangumiId=3352&subgroupid=636
 ```
 [屏幕截图 2024-08-16 040140](https://github.com/user-attachments/assets/ec56d4f1-dd47-4c71-91cc-bfa70a0b6875)

**Comment by tanmoumou252** [comment]
https://github.com/PBH-BTN/BTN-Collected-Rules#ip-%E8%A7%84%E5%88%99%E8%AF%B4%E6%98%8E

**Comment by IAALAI** [comment]
可以把它的ID复制出来吗?

**Comment by tanmoumou252** [comment]
> 可以把它的ID复制出来吗?

```
ޭ__
```
这是pbh项目地址里给的,具体能不能屏蔽到,这个不好说😑

**Comment by tanmoumou252** [comment]
![屏幕截图 2024-08-16 221012](https://github.com/user-attachments/assets/54169740-7eef-45ae-8284-46b0f96dec74)

还有`36.250.241.0/24` 这个ip

**Comment by tanmoumou252** [comment]
这类刷流量的,都有一个特点,就是可以突破你的客户端限速,跑满上行带宽,我还在用uTorrent的时候就感觉到了,感觉可以利用这个做功能
前提是开了客户端限速,比如上行40Mbps,限速16Mbps,10秒内整个客户端最多上传20~30MB,所以一定会小于上行占满的时候的50MB
```限速模式下,仍然有单ip跑满带宽,就一定是刷流量的```

**Comment by Simple-Tracker** [comment]
感谢反馈!

这是 ```\u07ad__```, 理论上已经在 blockList 内.

**Comment by tanmoumou252** [comment]
> 感谢反馈!
> 
> 这是 `\u07ad__`, 理论上已经在 blockList 内.

用\u07ad__去检索,确实可以看到有相同的issue,但是完全不清楚这个`ޭ__`是怎么打字打出来的,所以也没办法直接用`ޭ__`搜索

而且从体验上看这个`\u07ad__`屏蔽的效果不是很好,下载24G了也没触发屏蔽

**Comment by Simple-Tracker** [comment]
可以提供 InfoHash 或者 Magnet Link 用于测试吗? 这是一个很奇怪的问题.

**Comment by tanmoumou252** [comment]
> 可以提供 InfoHash 或者 Magnet Link 用于测试吗? 这是一个很奇怪的问题.

![Screenshot_20240817-202627_RustDesk](https://github.com/user-attachments/assets/6042a6b6-39d6-4c03-b071-f47b1ae65b6e)

客户端用火绒限速30KB/s，非常容易就抓到他了

`e40a200cbf42c6a056a5a2d328c890289fd11a87`

`36f760e47add0f6fd8f3017dd700ce119bda7719`

他从前天到现在一直都在刷恶魔的破坏，很可能明天老哥看到这条回复的时候，他还在刷，这两个是他现在此刻在刷的，要是明天底下没有他，就试试看第一条rss订阅里的其他磁力

因为他真的，每分钟都会出现在我控制台封禁日志里

**Comment by tanmoumou252** [comment]
![屏幕截图 2024-08-19 232409](https://github.com/user-attachments/assets/5e455ad4-25cd-49d0-b969-98d9fa4dde4d)

`125.77.27.0/24`

**Comment by Simple-Tracker** [comment]
已测试, 但非常遗憾的是: 我似乎无法连接对面. 不过, 我发现 222.185.229.0/24 Aria2 可能有比较可疑的行为.
由于上面显示的用户数为 0 (26), 猜测可能是 ```ignoreNoLeechersTorrent``` 选项导致无法正常屏蔽. 这可能是 qBittorrent 的下载用户数不准确的问题, 可以尝试进行关闭. 新版本将默认关闭此项.
