### ISSUE TITLE
Linux通过IPBlockListURL导入的IP黑名单不生效

### ISSUE THREAD

**Issue by SaltyFishPlus** [Simple-Tracker/qBittorrent-ClientBlocker#111]
环境是ubuntu qbittorrent-nox4.6.5配合qBittorrent-ClientBlocker
做了一个实验，将config.json中的IPBlockList设为空，只通过IPBlockListURL导入的IP黑名单，发现qbcb并没有正常拦截到异常IP
![image](https://github.com/user-attachments/assets/38cd2bea-c9af-49c0-b7bd-f07a07f2614a)

设置了IPBlockList则可以正常拦截
![image](https://github.com/user-attachments/assets/016c2630-7eee-4471-a644-9540dda40cd4)

**Comment by shellofsnail** [comment]
我在Docker版本中也有同样的问题，而且设置ipBlockListFile似乎也无法生效

**Comment by IAALAI** [comment]
我也遇到了，这会去就去排查

**Comment by Clackz** [comment]
windows版本貌似也有这个问题……

**Comment by Simple-Tracker** [comment]
感谢反馈!

近期正好有相关 PR 进行了改进 (但并不一定能修复), 可以测试一下此夜间版本: https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/actions/runs/10462173763

**Comment by IAALAI** [comment]
大概率是我并发的时候写错了吧。。。忘了把map换成线程安全的那一种了

**Comment by Simple-Tracker** [comment]
相信 3.5 系列新版本已解决此问题, 欢迎测试!
