### ISSUE TITLE
请求时发生了错误: 资源不存在

### ISSUE THREAD

**Issue by InspAlgo** [Simple-Tracker/qBittorrent-ClientBlocker#117]
Windows 11 23H2 
qBittorrent 4.6.6
qBittorrent-ClientBlocker 3.5b2 (windows, amd64)

出现了下面这个报错提示
```
[2024-08-30 14:40:13][Fetch] 请求时发生了错误: 资源不存在.
[2024-08-30 14:40:13][SetIPBlockListFromURL] 获取时发生了错误.
[2024-08-30 14:40:13][SetIPBlockListFromURL] 设置了 0 条 IP 规则 (来源: IPBlockListURL).
```
看了下 `config.json` 里的这个配置的 URL。
```json
"ipBlockListURL": [
    "https://bta.iaalai.cn/BTN-Collected-Rules/combine/all.txt",
    "https://cdn.jsdelivr.net/gh/PBH-BTN/BTN-Collected-Rules@main/combine/all.txt",
    "https://cdn.jsdelivr.net/gh/Simple-Tracker/qBittorrent-ClientBlocker@dev/blockIP.txt"
  ],
```
我将上面三个链接分别复制到浏览器中访问，发现 `https://cdn.jsdelivr.net/gh/Simple-Tracker/qBittorrent-ClientBlocker@dev/blockIP.txt` 无法访问，其他两个可以正常访问。

**Comment by IAALAI** [comment]
还好，问题不大。因为它们3个其实是同一个文件。。。

**Comment by Simple-Tracker** [comment]
> > 感谢反馈!
> > URL 配置错误, 下个版本修复!
> 
> 也遇到了同样的问题，有没有什么可供替换的URL？
> 
> ```
> [2024-09-28 13:39:37][SetBlockListFromURL] 获取时发生了错误.
> [2024-09-28 13:39:37][Fetch] 获取时发生了错误: Get "https://bta.iaalai.cn/BTN-Collected-Rules/combine/all.txt": EOF.
> [2024-09-28 13:39:37][SetIPBlockListFromURL] 获取时发生了错误.
> [2024-09-28 13:39:37][SetBlockListFromURL] 设置了 0 条 表达式 规则 (来源: BlockListURL).
> [2024-09-28 13:39:37][SetIPBlockListFromURL] 设置了 0 条 IP 规则 (来源: IPBlockListURL).
> [2024-09-28 13:39:47][Fetch] 获取时发生了错误: Get "https://bta.iaalai.cn/qBittorrent-ClientBlocker/blockList.json": EOF
> ```

默认已经配置了多个 URL, 若任意成功则无需特殊处理, 若均不成功可以尝试检查网络设置 (包括屏蔽器的代理设置).
