### ISSUE TITLE
2.4p10 以及之后版本无法在 macOS 上运行

### ISSUE THREAD

**Issue by UjuiUjuMandan** [Simple-Tracker/qBittorrent-ClientBlocker#12]
我下载的文件是 `qBittorrent-ClientBlocker-2.4p10-darwin-amd64.tar.gz` ，此文件以及之后版本的文件均无法运行。

fish: fish: Job 1, './qBittorrent-ClientBlocker' terminated by signal SIGSEGV (Address boundary error)
bash: Segmentation fault: 11
zsh: zsh: segmentation fault  ./qBittorrent-ClientBlocker

**Comment by Simple-Tracker** [comment]
感谢反馈!

问题已确认, 是由上游  UPX 压缩二进制的 bug 引起的 (https://github.com/upx/upx/issues/424).
将在 2.6b8 修复.

**Comment by Simple-Tracker** [comment]
Resolved! [2.6b8](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/releases/tag/2.6b8)
在 M1 设备上测试 ARM64 版本正常工作.
