### ISSUE TITLE
bitcomet好像无法正常使用

### ISSUE THREAD

**Issue by sblvbon** [Simple-Tracker/qBittorrent-ClientBlocker#124]
bitcomet2.8版本
3.5b4
有输出但是不生效
<img width="986" alt="image" src="https://github.com/user-attachments/assets/f52e9049-5aed-40b3-8bc8-88b830649a63">

**Comment by Simple-Tracker** [comment]
感谢反馈!

见此: https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/discussions/25#discussioncomment-10405407

**Comment by sblvbon** [comment]
不是作者的问题，bitcomet的webUI就没这功能😓
