### ISSUE TITLE
useShadowBan 是不是不支持旧版本qBittorrent？

### ISSUE THREAD

**Issue by GentAliang** [Simple-Tracker/qBittorrent-ClientBlocker#129]
qBittorrent 4.1.9.1提示未检测到 ShadowBan API, 将使用常规方法，用qBittorrentEE 4.6.6.10就没问题。
提示这个用起来也没差别吧？

**Comment by Simple-Tracker** [comment]
感谢反馈!

只支持 qBEE, 用起来一般没什么差别.

**Comment by GentAliang** [comment]
好的，谢谢解答
