### ISSUE TITLE
登录失败: 账号或密码错误

### ISSUE THREAD

**Issue by UjuiUjuMandan** [Simple-Tracker/qBittorrent-ClientBlocker#13]
我的 qBittorrent 版本是 4.6.3 ，我确认配置中的用户名和密码是正确的。
<img width="735" alt="Screenshot 2024-02-05 at 00 51 12" src="https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/125150101/3a9b9f36-0335-40dd-8f02-d64e18be1064">

您可以设置密码，并暂时关闭对本地地址跳过验证来确认。

**Comment by Simple-Tracker** [comment]
感谢反馈!

经过测试, 发现 Login 有一定概率会出现无限登录循环及登录请求会被发出多次的 bug, 但并无登录失败的问题.
这些问题将在即将发布的 2.6 版本中修复, 可以更新后再尝试问题是否解决.

**Comment by Simple-Tracker** [comment]
[2.6](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/releases/tag/2.6) 版本已发布!
