### ISSUE TITLE
blockList-Optional.json文件内容含中文会报错

### ISSUE THREAD

**Issue by dbox233** [Simple-Tracker/qBittorrent-ClientBlocker#131]
`[2024-09-22 21:40:34][SetBlockListFromFile] 构造 JSON 时发生了错误: blockList-Optional.json.`

系统：Linux OpenWrt 5.4.143 #0 SMP PREEMPT Wed Oct 6 13:26:37 2021 aarch64 GNU/Linux

**Comment by Simple-Tracker** [comment]
感谢反馈!

测试没有问题, 请确保其以 UTF-8 格式保存并格式正确 (尤其是原最后一行的逗号).

**Comment by dbox233** [comment]
重新测试了，发现是与中文无关，是注释问题，一含有注释（不管单行或多行）就报错
ps：但在config.json里有注释却没问题

**Comment by dbox233** [comment]
另测试时发现以下错误
`[2024-09-23 22:17:17][LoadLang] 解析语言文件时发生了错误: lang/en.json|invalid character '/' looking for beginning of object key string.
`
也是注释引起的问题

**Comment by Simple-Tracker** [comment]
晚些时候将试图修复此问题.

**Comment by dbox233** [comment]
没问题了
