### ISSUE TITLE
建议增加配置选项以使得发送给BT客户端的HTTP 请求不通过代理

### ISSUE THREAD

**Issue by Paindar** [Simple-Tracker/qBittorrent-ClientBlocker#134]
现在的qbcb，所有的HTTP请求使用的都是同一个HTTP Client，这使得：
1. 如果配置了Proxy，则所有发给bt客户端的都会通过Proxy，这对于qbcb和bt客户端都在同一个网络中的场合（例如都在同一台机器上）完全没有必要。
2. 如果未配置Proxy，则情况1不会发生，但从网络上获取网络资源（例如BlockList，或是检查更新？）有可能会失败。

因此，建议增加配置选项，以允许**仅发送给BT客户端的HTTP 请求不通过代理**。

**Comment by Simple-Tracker** [comment]
这是一个不错的建议, 尽管我在想怎么以简单的方式较好的实现它.

**Comment by Paindar** [comment]
现在已经有一个HttpClientWithoutCookies了，如果再叠一个NoProxy就会有四个不同的Client，实际上我有考虑过是不是直接让UpdateCheck和BlockListRequst单独走一个Client。

对局域网跳过代理有个小问题，徒增连接数。在NoProxy下，连接是QBCB->BTClient。而如果委托Proxy去甄别的话就会多一个连接：QBCB->Proxy->BTClient。又因QBCB对于每一个Block条目都会发送一个Request，我会担心是否会因耗尽连接数导致Request失败。

**Comment by Simple-Tracker** [comment]
Done. https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/commit/ec40ccfe6ba0dc835258520d0ba7943e32f93ce7 Nightly build: https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/actions/runs/11532819371

修改 Config Proxy 原有逻辑为如下:  
空: 禁止使用代理; **Auto: 自动 (仅对外部资源使用代理)**; All: 使用代理
