### ISSUE TITLE
可疑的新客户端

### ISSUE THREAD

**Issue by LightmoonXD** [Simple-Tracker/qBittorrent-ClientBlocker#22]
观察到异常下载行为，可能需要更多证据。
![截屏2024-03-02 11 07 57](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/21337686/e6a2c14c-e3f3-4a45-95b0-a88142ea6d7e)

**Comment by Simple-Tracker** [comment]
感谢反馈!

已有支持 IPUpCheckIncrementMB (IP 全局上传增量大小), 并在 [2.9b3](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/releases/tag/2.9b3) 支持设置 IPUpCheckPerTorrentRatio. (IP 单个 Torrent 上传增量倍率)

若 IP 全局上传增量超限 或 IP 单个 Torrent 上传增量超限, 则会封禁 Peer. 希望能缓解此问题.

另: 由于近期观察到客户端改名趋势, 因此进一步增加客户端屏蔽列表将收效甚微, 除非其规模大到足以引起广泛关注, 否则不倾向于加入此客户端进入默认列表. 而相关增强功能由于未经完善测试, 因此为避免高出错率均为默认关闭, 但鼓励用户使用及测试.

**Comment by shellofsnail** [comment]
比较大的可能也是，因为我检测到该客户端的IP与anacrolix是同一个子网

**Comment by JockeyWang** [comment]
这个客户端基本上可以认为需要屏蔽了，建议加规则看看。
"dt/torrent/v1.00"

**Comment by Simple-Tracker** [comment]
后续观察, 由于其确实属于同一/相近子网, 可假定其规模足够大, 因此下一版本将加入屏蔽列表.

**Comment by chuyinluotian01** [comment]
![f9ce1b1f80e016e9b5863f1ad42a36db](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/53629507/2a664298-22d6-4e66-b20f-f5c4241ae662)
已经开始泛滥了

**Comment by Simple-Tracker** [comment]
[2.9](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/releases/tag/2.9) 已发布!

添加 dt/torrent 及 trafficconsume 至默认屏蔽列表.

**Comment by JockeyWang** [comment]
还有个事情，之前我使用2.9的默认配置，遇到一个transaction也有异常行为，但没有触发屏蔽。
500M的种子已经拖了1.5G

**Comment by Simple-Tracker** [comment]
> 还有个事情，之前我使用2.9的默认配置，遇到一个transaction也有异常行为，但没有触发屏蔽。 500M的种子已经拖了1.5G，而且这货不是连续下载，大概是每20秒左右请求2秒钟。

默认配置未启用增强自动屏蔽, 可手动编写规则将异常客户端放入 blockList, 也可参考[配置 Config](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker#配置-config)启用相关功能.

**Comment by JockeyWang** [comment]
> > 还有个事情，之前我使用2.9的默认配置，遇到一个transaction也有异常行为，但没有触发屏蔽。 500M的种子已经拖了1.5G，而且这货不是连续下载，大概是每20秒左右请求2秒钟。
> 
> 默认配置未启用增强自动屏蔽, 可手动编写规则将异常客户端放入 blockList, 也可参考 [配置 Config](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker#%E9%85%8D%E7%BD%AE-config) 启用相关功能.

banByPUStartPrecent和banByRelativePUStartPrecent，type看起来为uint32，这么至少要到1%才满足要求。
我希望设置0.2%的话，看起来做不到？
顺带一提，10MB的阈值倒是可以往上改一改。
