### ISSUE TITLE
Application hangs after failing to print -XL0012- random peer id

### ISSUE THREAD

**Issue by AutismGaming228** [Simple-Tracker/qBittorrent-ClientBlocker#27]
![image](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/38699033/ebfb7b92-3590-4887-a3d0-32a589b0ca40)

After some time, the -XL0012- peer will be encountered, but because of the PEER ID randomness of that client, ClientBlocker fails to print PEER ID and hangs, stops responding and stops banning other clients.

一段时间后，会遇到 -XL0012- 对等体，但由于该客户端的 PEER ID 是随机的，ClientBlocker 无法打印 PEER ID，因此会挂起，停止响应，并停止禁止其他客户端。

**Comment by Simple-Tracker** [comment]
感谢反馈!

可尝试[此版本](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/actions/runs/8173991743)并观察是否恢复正常, 此版本会将所有非 ASCII 字符转换为 Unicode 代码表示.


Thanks for the feedback!

Try [this version](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/actions/runs/8173991743) and see if the behavior is normal. This version converts all non-ASCII characters to Unicode code representation.

**Comment by AutismGaming228** [comment]
![image](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/38699033/ca8ae519-0be2-4611-a223-e9896e727604)

I think the fix works. However, as -XL0012- crash was random, I will need to test for more time. I will report here in 12 hours

我认为修复是有效的。不过，由于 -XL0012- 崩溃是随机的，我需要更多时间进行测试。我将在 12 小时后在此报告

**Comment by AutismGaming228** [comment]
我相信这已经奏效。谢谢！

I believe this has worked. Thanks!

**Comment by Simple-Tracker** [comment]
若有相同或相似问题, 可于 Issue 继续追加.

If you have the same or similar questions, you can continue to add them in the Issue.
