### ISSUE TITLE
Add go.torrent to blockList

### ISSUE THREAD

**Issue by IAALAI** [Simple-Tracker/qBittorrent-ClientBlocker#28]
![cba4a94f478d9eddf3f0016e59b1e552](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/50038322/0c34c453-e888-4ea0-a402-25816cacc35a)
![f7107ea19ae4d42b35b586274f26847b](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/50038322/2ae16203-3ad0-4974-81c6-f2e200cc9e1f)
确定这个IP段就是 anacrolix 的那个

**Comment by IAALAI** [comment]
"go.torrent dev \d+" 这样可行不？

**Comment by IAALAI** [comment]
> 可以在原 PR 分支上进行进一步的修改, 会自动追加到 PR 上, 只要误匹配其它客户端的几率不大, 宽泛一些是可以接受的. 客户端的屏蔽逻辑是: 当客户端的某个字符串屏蔽到正则, 所以这是后 `.*` 没有必要的原因之一.
> 
> 由于此客户端事实上已被 anacrolix/torrent 取代, 因此将其所有版本都屏蔽并非不可接受的做法, 因此我在 PR 中的建议结合起来的正则表达式其实会是这样的: `"go[ \.]torrent"`, 它会匹配所有 `*go torrent*` 或 `*go.torrent*` 的客户端.

我傻了，我忘了PR里面的提交可以改了。。。

**Comment by Simple-Tracker** [comment]
[3.0b2](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/releases/tag/3.0b2) 已发布!
