### ISSUE TITLE
建议增加对17777端口的检测

### ISSUE THREAD

**Issue by JockeyWang** [Simple-Tracker/qBittorrent-ClientBlocker#33]
最近这批疯狂下载的客户端，不少开放了17777端口。
能否以此做个规则判定呢？

**Comment by Simple-Tracker** [comment]
暂不考虑添加, 原因在于这本质上是利用“信息差”趁对方没关注到时进行的规则封禁, 且其具有影响检测性能的副作用 (对用户网络连接的每个 Peer 造成大量检测请求).

个人更关注如何在机制上解决问题.

**Comment by JockeyWang** [comment]
原来如此，那看来是我考虑不周了。

**Comment by Simple-Tracker** [comment]
另: 也可考虑尝试另一个屏蔽器: https://github.com/Ghost-chu/PeerBanHelper, 前段时间关注到其更新了该功能.
