### ISSUE TITLE
Tai-pei torrent dev

### ISSUE THREAD

**Issue by RtYkk** [Simple-Tracker/qBittorrent-ClientBlocker#36]
99% 是恶心人的 client。
今天在 218.92.139.135 和 218.92.139.138 发现两个。
与该[文档](https://docs.qq.com/doc/DQnJBTGJjSFZBR2JW)比对一致。

> 其中218.92.139.0-218.92.139.255使用的工具为Taipei-Torrent dev。

该[客户端](https://github.com/jackpal/Taipei-Torrent)已经六年没更新，基本不可能有正常用户。

**Comment by RtYkk** [comment]
duplicate #35

**Comment by RtYkk** [comment]
我先用 IP 屏蔽了

**Comment by Simple-Tracker** [comment]
#35 已实现, 且3.0 版本的默认屏蔽规则已包含此客户端.
