### ISSUE TITLE
将Windows端注册为Windows服务

### ISSUE THREAD

**Issue by Yastruhank** [Simple-Tracker/qBittorrent-ClientBlocker#37]
考虑到在目前Windows端缺少合理的隐藏窗口的方案，请问是否考虑将软件注册为Windows服务，以在后台静默运行不显示窗口呢？

**Comment by Simple-Tracker** [comment]
感谢反馈!

这也是我们在 Discussion (https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/discussions/32#discussioncomment-8842972) 提到的内容之一, 没想到能如此快的看到实现.

**Comment by Simple-Tracker** [comment]
由于不鼓励为 Feature 发起 Pull Request 时同步创建 Issue, 故关闭, 于 PR 内继续追踪.
