### ISSUE TITLE
[Feature Request] Docker image

### ISSUE THREAD

**Issue by ljcbaby** [Simple-Tracker/qBittorrent-ClientBlocker#4]
如题

**Comment by lslqtz** [comment]
这是很好的功能, 但是我不会写 Dockerfile, 所以...

**Comment by Simple-Tracker** [comment]
这是很好的功能, 但是我没用过 Docker 不会写 Dockerfile, 所以...

**Comment by ljcbaby** [comment]
Dockerfile 等我考完期末可以试试。包括 action

**Comment by Simple-Tracker** [comment]
已尝试发布 Docker 版本, 该版本未经测试.
https://hub.docker.com/r/simpletracker/qbittorrent-clientblocker/tags
通过在 Dockerfile 将所有系统环境变量转为 JSON, 达到了避免修改程序的效果.
```
RUN (jq -n 'env|to_entries[]|{(.key): (.value|tonumber? // .)}' | jq -s add) > /app/config.json
```
