### ISSUE TITLE
请问大佬，为什么运行屏蔽器后会一直重置qBittorrent的自动添加tracker的设置

### ISSUE THREAD

**Issue by nj1067426682** [Simple-Tracker/qBittorrent-ClientBlocker#42]
![PLKY T `U7EEAE{N`3A~SBQ](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/77059338/c8079721-d956-4f30-bf4e-9b36429b4795)
qBittorrent版本4.3.0
qBittorrent-ClientBlocker版本windows-amd64 3.0

**Comment by Simple-Tracker** [comment]
感谢反馈!

一直在使用, 并无此问题, 建议升级 qBittorrent 后再测试.

**Comment by nj1067426682** [comment]
> 感谢反馈!
> 
> 一直在使用, 并无此问题, 建议升级 qBittorrent 后再测试.

好的，我这边自己排查一下，谢谢大佬
