### ISSUE TITLE
[enhancement] 建议支持多个qb连接配置

### ISSUE THREAD

**Issue by xiaozhikang0916** [Simple-Tracker/qBittorrent-ClientBlocker#44]
我同时运行着多个qb实例，分别用来下载不同类型的内容，希望这个程序能同时配置多个qb连接

**Comment by Simple-Tracker** [comment]
感谢反馈!

暂时不考虑添加, 原因为: 同时配置多个连接会增加程序复杂度, 还会使程序配置及日志变得复杂.

建议的替代方案: 以 Docker 容器或服务形式多开客户端.

**Comment by xiaozhikang0916** [comment]
感谢解答，看来要给所有的compose.yaml都复制一份屏蔽器服务了

**Comment by xiaozhikang0916** [comment]
追加一个提问，启动配置可以环境变量和配置文件共存吗

在`qBURL`不能有多值的情况下，我可能启动多个blocker实例、共享同一个config配置，并通过启动时的环境变量控制连接不同的qb实例，减少重复配置的工作

**Comment by Simple-Tracker** [comment]
目前还不能.

**Comment by mzhboy** [comment]
一个简单的方法是链式加载配置文件，这在linux应用中很普遍。
不同的实例配置加载各自的配置文件并且链式加载一个共同的配置文件。

**Comment by Simple-Tracker** [comment]
> 一个简单的方法是链式加载配置文件，这在linux应用中很普遍。 不同的实例配置加载各自的配置文件并且链式加载一个共同的配置文件。

谢谢! 这是一个很好的解决方案.
[3.2b6](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/releases/tag/3.2b6) 中已支持这种模式.

**Comment by Simple-Tracker** [comment]
由于上述原因及新的支持的加入, 视作已完成, 若有问题, 可再度打开此 Issue!
