### ISSUE TITLE
对于文档中配置一节的建议

### ISSUE THREAD

**Issue by zhongfly** [Simple-Tracker/qBittorrent-ClientBlocker#5]
我建议默认值这一列不应该带有单位或混杂其他说明，而是实际的默认值。例如：
banByPUStartPrecent 2%
应该改写为
banByPUStartPrecent 2
对于普通用户，如果不看代码，他无法知道写到配置文件里时是不能带上百分号%的，极有可能被此处误导。而且也不知道必须是一个整数

可以考虑把单位放到后面的说明里，或者单独一列说明单位或者可填入的值（整数？字符？true或false？）

**Comment by Simple-Tracker** [comment]
感谢反馈!
1. 程序启动后会载入配置文件, 无论是否载入失败均会列出当前配置, 而列出的配置中无相关附注;
2. 已对文档进行优化, 将 单位/修饰/备注 等放入括号内, 括号及其内容不应填入;
3. 由于大部分配置项均有默认, 因此用户并无必要完全修改每一项;

**Comment by zhongfly** [comment]
另外，倍率和百分比这样的可以改成浮点数吗？

**Comment by Simple-Tracker** [comment]
没有计划对这类滞后防误判相关参数使用更细致的选项, 尤其是此处已是百分比使用浮点数可能更加难理解.
这些参数的最小对大型 Torrent 看起来可能偏大, 但对小型 Torrent 来说却是比较合理的最低值.

对于绝对而言, 在设计时, 考虑的大小通常为 10MB/100MB/1000MB (Torrent 百分比 1%: 0.1MB/1MB/10MB), 若 Peer 汇报百分比 计算得到之 绝对下载量 与 客户端绝对上传量 差为 10MB, 则其最低 1 倍即为 10MB, 以上是对于小型 Torrent 在参数允许范围内可设定的最低值.
对于相对而言, 此值往往只会比上述相近或更低.
