### ISSUE TITLE
失败时返回0

### ISSUE THREAD

**Issue by soiamsoNG** [Simple-Tracker/qBittorrent-ClientBlocker#50]
[RunConsole] 认证失败

失败后程序返回 0， 应该返回一个比0大的数值
或定义几个数值方便其他程序控制

**Comment by Simple-Tracker** [comment]
https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/actions/runs/8601944877

此 Nightly Build 版本将在首次程序认证失败时返回 1, 这一改动会于后期发布于 3.2, 但值得注意的是: 这不包括其它不会导致程序结束的时间, 如 QBURL 为空包括程序未能检测到 qBittorrent 路径时程序并不会停止.

**Comment by Simple-Tracker** [comment]
在 3.2b2/3.2b3 中完成.
