### ISSUE TITLE
疑似新改名客户端hp/torrent/v2.01

### ISSUE THREAD

**Issue by lrhtony** [Simple-Tracker/qBittorrent-ClientBlocker#53]
![image](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/54092711/7e0ca703-ac41-40d4-97a6-fd83f3ac5d82)
ip段、客户端、以及抢占带宽这些特征都跟之前的十分相像

**Comment by Simple-Tracker** [comment]
感谢反馈!

已添加并发布 [3.2b2](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/releases/tag/3.2b2), 不过我也要引用 qBEE Release Note 的一句话: ```Just a cat and mouse game :|```.
