### ISSUE TITLE
功能需求 https

### ISSUE THREAD

**Issue by RangeZero** [Simple-Tracker/qBittorrent-ClientBlocker#54]
是否可以增加https连接webui的支持？同时自定义webui访问链接及端口

**Comment by Simple-Tracker** [comment]
感谢反馈!

这是已支持功能, 请参见配置 Config 中的 ```qBURL```/```skipCertVerification```.

**Comment by RangeZero** [comment]
抱歉，是我没仔细看文档，问题已解决
