### ISSUE TITLE
Microsoft Defender 误报？

### ISSUE THREAD

**Issue by shugen002** [Simple-Tracker/qBittorrent-ClientBlocker#55]
似乎被微软这边误报了
https://www.virustotal.com/gui/file/e652758365eede16763e6c3916242750856c4185b9e52eac2aa2bc4da9a64f8b/detection
建议琢磨下 https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by shugen002** [comment]
经典UPX误报...

**Comment by shugen002** [comment]
看了下，好像就算没压也不算很大的说。。。

**Comment by Simple-Tracker** [comment]
> 看了下，好像就算没压也不算很大的说。。。

~~主打一个追求极致.~~

**Comment by shugen002** [comment]
> > 看了下，好像就算没压也不算很大的说。。。
> 
> ~主打一个追求极致.~

~那就在外面zip那层追求极致吧~

**Comment by Sanlorng** [comment]
> > > > 看了下，好像就算没压也不算很大的说。。。
> > > 
> > > 
> > > ~主打一个追求极致.~
> > 
> > 
> > ~那就在外面zip那层追求极致吧~
> 
> [3.2b5](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/releases/tag/3.2b5) 已不再使用 UPX 压缩程序体积了, 可再度测试一下情况.
> 
> 如果你注意的话, 会发现相比 3.1 版本在压缩后体积也增加了约 0.5MB.
3.4p8依然误报
![image](https://github.com/user-attachments/assets/dd405273-029a-42e8-b895-b5f2d5c55eb2)
