### ISSUE TITLE
功能建议 软件开启时自动更新或自动检测新版本

### ISSUE THREAD

**Issue by FarstarD** [Simple-Tracker/qBittorrent-ClientBlocker#56]
是否能增加启动时自动检测并下载新的二进制文件自动替换旧版本的功能呢？或者自动检测最新版本提示更新？

**Comment by Simple-Tracker** [comment]
感谢反馈!

做此功能不难, 相对比较难的是如何稳定可靠的连接 GitHub...

**Comment by Simple-Tracker** [comment]
已完成, 在 3.2 的后期版本中将可自动检测新版本, 检测的默认间隔为 86400 秒即 1 天, 检测到需要更新的逻辑如下:
1. 获取到的最新主版本 大于 屏蔽器自身主版本;
2. 获取到的最新主版本 等于 屏蔽器自身主版本, 但最新次版本 大于 客户端自身次版本;
3. 获取到的最新主版本 等于 屏蔽器自身主版本, 且最新次版本 等于 客户端自身次版本, 但最新补丁版本 (b1/p1) 大于客户端自身补丁版本;

Public 版本只会和 Public 版本对比版本, 因此, 每次检测最多提示一次更新.
Beta 版不仅会与 Beta 版对比版本, 还会与 Public 版对比版本, 因此, 每次检测最多提示两次更新.

**Comment by Simple-Tracker** [comment]
[3.2b10](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/releases/tag/3.2b10) 已发布!

**Comment by Simple-Tracker** [comment]
3.2 已发布, 视作已解决!
