### ISSUE TITLE
减少或尽量避免对配置文件的破坏性改动

### ISSUE THREAD

**Issue by zhongfly** [Simple-Tracker/qBittorrent-ClientBlocker#57]
希望减少或尽量避免破坏性改动，特别是如今增加了自动更新（而且是强制开启的？），容易出现某一天突然设置失效的问题。

**Comment by Simple-Tracker** [comment]
感谢反馈!

对 URL/Username/Password 的破坏性改动是因加入了 Transmission 支持 (若未来稳定及支持更多客户端后项目亦有可能改名).
对 ipfilterURL 的破坏性改动是因和当前 ipBlockList 设置项有一定不一致.

Beta 版本默认并非 Latest, 因此, 这对非 Docker 版本用户没有影响 (Docker 版本目前会默认推送 Beta).

另: 原本计划今天发布 3.2 版本, 由于此 Issue, 再推迟一段时间以便用户做好相关应对.

**Comment by zhongfly** [comment]
Username/Password 这个之前就是2.1改掉的，现在又改回近似的client*

> Config 内 username 更名为 qBUsername, Config 内 password 更名为 qBPassword.

就算再支持更多种客户端，我觉得实在是没啥必要再换名字了，含义都差不多

如果真有变化，希望考虑向下兼容，例如保留旧选项，只增加单独的选项。

**Comment by Simple-Tracker** [comment]
向下兼容是好事, 只是...太麻烦了.
确实是当时确定时考虑不周, 不过像这种重要设置项不会有下次了, 如果有, 那一定会有向下兼容
