### ISSUE TITLE
是否有方法将config.json放置在docker的Volumes里

### ISSUE THREAD

**Issue by JedSunCN** [Simple-Tracker/qBittorrent-ClientBlocker#60]
Volumes中创建了个“qBittorrent-ClientBlocker_config”的卷，
将启动配置中 `-v /path/config.json:/app/config.json`改成了`-v qBittorrent-ClientBlocker_config:/app`（配置文件在volume的目录中），便于管理。

启动时报错`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./entrypoint.sh": stat ./entrypoint.sh: no such file or directory: unknown.`

请问有什么方法解决配置文件不能放volume中的问题？谢谢。

**Comment by Simple-Tracker** [comment]
感谢反馈!

解决方案: 只映射 config.json 而非映射整个目录.

**Comment by JedSunCN** [comment]
docker的volume to container好像只能挂载目录而不是文件，只映射文件好像不能走数据卷的路子。🤣

**Comment by Simple-Tracker** [comment]
没有很好的方案, 可能 Volume 它就不适合此程序.

建议按之前的方式使用, 改变 path 为自定义的 path 方便管理. 若为 Docker 提供通过环境变量指定配置文件路径的功能, 将 Volume 挂到其它路径后通过环境变量使用, 相比现在的方案有什么优势吗?

**Comment by Simple-Tracker** [comment]
由于一周无活跃, 先行关闭. 若有问题可再度打开.
