### ISSUE TITLE
Docker版本读取配置文件出错

### ISSUE THREAD

**Issue by LogicDX342** [Simple-Tracker/qBittorrent-ClientBlocker#61]
貌似 Docker 和 x86 读取 config 时用的 key 不同。
把 x86 的 config.json 复制给 Docker， 结果运行时提示 ClientURL 为空，但能正确读取 BolckList。x86 版的 log 用的是QBURL，我就尝试把 config 里的 qbURL 换成 clientURL，问题解决。username 和 password 也有这个问题

**Comment by Simple-Tracker** [comment]
感谢反馈!

3.2 破坏性改动:
Config 内 qBURL 更名为 clientURL.
Config 内 qBUsername 更名为 clientUsername.
Config 内 qBPassword 更名为 clientPassword.
Config 内 ipFilterURL 更名为 ipBlockListURL.

**Comment by LogicDX342** [comment]
忘记看log了，我的问题 b38
