### ISSUE TITLE
客户端屏蔽有迅雷的漏网之鱼

### ISSUE THREAD

**Issue by Shiki-zs** [Simple-Tracker/qBittorrent-ClientBlocker#64]
![Snipaste_2024-04-19_22-03-53](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/53854189/520a5962-f654-41b5-8b16-0482026ebc26)

最近频繁遇到 XunLei 0019 客户端吸血，已有的屏蔽规则没覆盖，暂时在自己本地新加了一条 "^XunLei *?\\d+"

**Comment by Simple-Tracker** [comment]
谢谢! 已经修改规则, 但听说 XL0019 实际上在下载阶段会有上传.

**Comment by AkkarinME** [comment]
> 谢谢!已经修改规则, 但听说 XL0019 实际上在下载阶段会有上传.

我用最新的3.3b5还是有XL0019的漏网之鱼，以及出现了XL0012一堆符号的漏网之鱼
![QQ图片20240422191907](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/162981575/1145f6e8-aa94-4a53-902e-7791d6cb5228)
![QQ图片20240422191918](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/162981575/2edb2739-7e43-4ce9-a257-b14a44c3956a)

**Comment by Simple-Tracker** [comment]
> > 谢谢!已经修改规则, 但听说 XL0019 实际上在下载阶段会有上传.
> 
> 我用最新的3.3b5还是有XL0019的漏网之鱼，以及出现了XL0012一堆符号的漏网之鱼 ![QQ图片20240422191907](https://private-user-images.githubusercontent.com/162981575/324443439-1145f6e8-aa94-4a53-902e-7791d6cb5228.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDE4NDUsIm5iZiI6MTcxMzgwMTU0NSwicGF0aCI6Ii8xNjI5ODE1NzUvMzI0NDQzNDM5LTExNDVmNmU4LWFhOTQtNGE1My05MDJlLTc3OTFkNmNiNTIyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNTU5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDViZjA0MzA0MjU0ZjFmYjk1YTg0NDY0NGM1N2U5YjU3MjQyNjE5NzYwNTUyNTg5NmFhNDI5NTFhZjgzMjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ok35uQRX-AeoyEdkZYoq3nDOT0d0AfoAQhmaeoWnI88) ![QQ图片20240422191918](https://private-user-images.githubusercontent.com/162981575/324443446-2edb2739-7e43-4ce9-a257-b14a44c3956a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDE4NDUsIm5iZiI6MTcxMzgwMTU0NSwicGF0aCI6Ii8xNjI5ODE1NzUvMzI0NDQzNDQ2LTJlZGIyNzM5LTdlNDMtNGNlOS1hMjU3LWIxNGE0NGMzOTU2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNTU5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWNkZmEzNTc2ZTQwNGZkY2RlZWE5OTM5NzA5ZmNmZWQ1ODExZGQ3ZjkxYWNkMTkxZGI3YTA5ZmQ4N2EzZjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G24QpAv4mU53uMIPoTxNeIufsxm0QxE7vUciHvkE0Ww)

客户端需要有上传或下载速度才会被封禁.

**Comment by Simple-Tracker** [comment]
另: 在未来版本中, 客户端封禁逻辑将优化为只有增强自动屏蔽会使用上传或下载速度进行封禁, 以同时改善准确率及封禁匹配率.
