### ISSUE TITLE
可疑的transmission 2.94

### ISSUE THREAD

**Issue by CXLmiewu** [Simple-Tracker/qBittorrent-ClientBlocker#65]
下载了一个win7系统镜像，一大堆这个transmission 2.94跑满上传。
![image](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/14076231/b467b48c-10bc-4294-97e6-eec5ae1e09ff)

**Comment by JockeyWang** [comment]
27.156.139.0-27.156.139.255
27.156.176.0-27.156.176.255
27.157.62.0-27.157.63.255
27.157.89.0-27.157.89.255
27.158.54.0-27.158.54.255
27.159.173.0-27.159.173.255
36.248.181.0-36.248.181.255
39.171.34.0-39.171.34.255
39.171.61.0-39.171.61.255
39.172.52.0-39.172.52.255
42.242.132.0-42.242.132.255
42.242.139.0-42.242.139.255
42.242.142.0-42.242.142.255
42.242.151.0-42.242.151.255
42.242.248.0-42.242.248.255
59.58.42.0-59.58.42.255
59.58.116.0-59.58.117.255
59.60.76.0-59.60.79.0
59.60.84.0-59.60.87.0
59.60.152.0-59.60.152.0
106.58.42.0-106.58.44.255
110.83.135.0-110.83.135.255
110.85.89.0-110.85.89.255
112.114.38.0-112.114.41.255
114.100.143.0-114.100.143.255
114.221.2.0-114.221.2.255
122.233.105.0-122.233.107.0
117.26.235.0-117.26.235.255
117.26.238.0-117.26.238.255
120.35.190.0-120.35.190.255
120.38.146.0-120.38.147.255
120.40.135.0-120.40.135.255
120.40.160.0-120.40.161.255
120.43.45.0-120.43.45.255
120.43.54.0-120.54.45.255
121.205.254.0-121.205.254.255
140.224.156.0-140.224.157.255
182.243.14.0-182.243.16.255
182.243.24.0-182.243.25.255
182.243.36.0-182.243.38.255
182.243.55.0-182.243.55.255
182.243.58.0-182.243.58.255
218.62.195.0-218.62.195.255
218.68.30.0-218.62.31.255
218.86.23.0-218.86.23.255
220.164.208.0-220.164.209.255
220.164.213.0-220.164.215.255
222.220.135.0-222.220.135.255
222.220.145.0-222.220.145.255
222.220.149.0-222.220.149.255
222.220.184.0-222.220.185.255

我整理了个IP列表，为防止误封，以一个v4/24出现3个IP为准，不过晚上测试发现它们已经消失了。

**Comment by Simple-Tracker** [comment]
感觉挺没规律的, 也许不一定扎堆在一个 Torrent 上, 真奇怪.

**Comment by Simple-Tracker** [comment]
这些 IP 相信已在最新的默认屏蔽列表中!
