### ISSUE TITLE
建议：每次更新可以自动合并配置文件

### ISSUE THREAD

**Issue by SteveYu000** [Simple-Tracker/qBittorrent-ClientBlocker#66]
每次更新后配置文件要么替换成新的，要么需要自己手动合并新的规则。能不能每次更新的时候自动把新规则合并进原配置文件，或者另建一个用户自定义配置文件，这样更新的时候就不会覆盖原来的自定义配置了。

**Comment by Simple-Tracker** [comment]
感谢反馈!

很好的想法, 就是有亿点麻烦. 目前有附加配置文件功能, 它应会覆盖主配置文件的配置, 可以尝试以它作为用户配置文件使用.

**Comment by dbox233** [comment]
现在有blockListURL选项的情况下，我建议将blockList选项独立为一个文件来维护，blockListURL再加上自动更新间隔和代理配置的支持就行
可以的话再加上个blockListFile这样的选项方便对blockList有定制需求的用户

**Comment by IAALAI** [comment]
感觉意义有限，只要不是频繁对配置进行破坏性的改动感觉进行修改没有什么显著意义。但是把blockList独立出来倒是确实可行

**Comment by Simple-Tracker** [comment]
3.4p3 已支持独立使用 blockListFile 及 ipBlockListFile, 其规则与 URL 类似, 一行一条.
