### ISSUE TITLE
位于ipBlockList内的ip没有被屏蔽

### ISSUE THREAD

**Issue by Trustedinstall** [Simple-Tracker/qBittorrent-ClientBlocker#69]
![无标题](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/68763785/339b6432-eb10-4750-a48e-1f716673329f)
123.159.200.0/24和2408:8740:31fe:19::/64这个段下都是这吸血客户端
看上去是没有获取到正确的端口号，增强屏蔽的功能也没有触发。

**Comment by Simple-Tracker** [comment]
感谢反馈!

这是屏蔽了, -1 代表全端口屏蔽, 客户端没有反应可能是客户端的迟滞问题.

**Comment by Trustedinstall** [comment]
已经等了很久了还是没被屏蔽，正常被屏蔽的话会显示“此次封禁客户端：x个”目前只能在qbittorrent内手动屏蔽

**Comment by Simple-Tracker** [comment]
我测试一下...

**Comment by Simple-Tracker** [comment]
试试 [3.3b9](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/releases/tag/3.3b9)!

**Comment by Trustedinstall** [comment]
那个ip现在还没出现，还不知道效果。
那么增强屏蔽功能也没生效也是这个原因吗？这个ip最后都产生了一个多G的传输量且进度一直都是0，已经符合增强屏蔽的标准了，都没被屏蔽还是被我手动屏蔽的。是因为屏蔽ip的优先级比增强屏蔽高吗？

**Comment by Trustedinstall** [comment]
> 那个ip现在还没出现，还不知道效果。 那么增强屏蔽功能也没生效也是这个原因吗？这个ip最后都产生了一个多G的传输量且进度一直都是0，已经符合增强屏蔽的标准了，都没被屏蔽还是被我手动屏蔽的。是因为屏蔽ip的优先级比增强屏蔽高吗？

那个ip出现了，屏蔽有效。

**Comment by Simple-Tracker** [comment]
是的, 屏蔽 IP 的优先级比增强屏蔽高. 这个版本的描述还有一些 bug: 最后"因 IP 地址而封禁"实际上是此次的数据.
