### ISSUE TITLE
每次开机，初次启动一段时间后闪退

### ISSUE THREAD

**Issue by XiaoBu39** [Simple-Tracker/qBittorrent-ClientBlocker#72]
每次开机，初次启动一段时间后闪退，但第二次启动后能运行很久
版本 3.3
Win11 22H2
![image](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/46661224/d8e2273e-805c-4cfb-9d4f-1f664df50d1f)

**Comment by Simple-Tracker** [comment]
感谢反馈!

请尝试在 cmd/PowerShell 等窗口运行, 并附上崩溃退出后的留下的错误报告.

**Comment by XiaoBu39** [comment]
依旧无错误信息，看起来是疑难杂症了
![image](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/46661224/5148c61d-e931-41a0-9d8d-295efc77ba52)

**Comment by Simple-Tracker** [comment]
[3.4b1](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/releases/tag/3.4b1) 加入了捕获崩溃日志的功能, 不确定对此种情况有没有用.

**Comment by XiaoBu39** [comment]
> [3.4b1](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/releases/tag/3.4b1) 加入了捕获崩溃日志的功能, 不确定对此种情况有没有用. 看起来, 这是一个非自然停止, 而且是程序所不能捕获的停止, 否则, 程序应会输出崩溃或停止信息.

试验了几天，3.4b1版本没有闪退现象，今天中午再启动了下3.3的，1小时多还是闪退了，看来新版本无意中解决了这个问题？

**Comment by Simple-Tracker** [comment]
解决就好!
