### ISSUE TITLE
 user friendly 用户友好性|[Fetch] 请求时发生了错误: 禁止访问.

### ISSUE THREAD

**Issue by specked2527** [Simple-Tracker/qBittorrent-ClientBlocker#74]
我觉得可以在.md写上
```
关于 
[Fetch] 请求时发生了错误: 禁止访问.
 这是正常可以忽略的信息
```

不应该假设用户会用你的产品 

```
使用教程
必须修改文件夹内的config.json文件, 并填写 
clientURL：你的webui地址，列如http:127.0.0.1:1234/
clientUsername：用户名
clientPassword：密码
```

是的你已经写了，但这个更方便新人

`fetchFailedThreshold	int	0 (禁用)	最大获取失败次数. 当超过设定次数, 将执行设置的外部命令
execCommand_FetchFailed	string	空	执行外部命令 (FetchFailed). 首个参数被视作外部程序路径, 当获取失败次数超过设定次数后执行`

**Comment by Simple-Tracker** [comment]
感谢反馈!

没看懂, 但欢迎 PR.
