### ISSUE TITLE
【Bug?】开启之后qbittorrent里面用户为空白

### ISSUE THREAD

**Issue by SteveYu000** [Simple-Tracker/qBittorrent-ClientBlocker#76]
如果开启clientblocker，用户那一栏就是空白（偶尔会正常），关闭之后再重启客户端就能恢复。web端能正常显示。这可能是什么原因，和clientblcker有关吗
![2024-06-02_021710](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/111431635/8810ee7a-31b7-4e04-8dcc-a0ad2cdc174e)

**Comment by Simple-Tracker** [comment]
感谢反馈!

除非屏蔽规则不合理将所有用户屏蔽, 不然通常不会出现此问题. 因此, 这可能是 qBittorrent 自身的 bug.

**Comment by SteveYu000** [comment]
好的，谢谢
