### ISSUE TITLE
遇到一种能正常汇报进度的吸血方式

### ISSUE THREAD

**Issue by Trustedinstall** [Simple-Tracker/qBittorrent-ClientBlocker#78]
115.231.84.128-136这个ip段发现集中在Windows镜像资源下。
特征就是首次连接时以随机的进度开始。低速传输，速度也就几十到几百kb，汇报的进度会增加但只和上传量有关。
进度越高传输越慢，最后停止传输，然后换另一个ip重复上面过程，由于单个ip传输量不会超过种子大小，且我并没有24小时开机运行，所以无法触发ip上传增量检测。
我也是第二天开机发现这些ip又以上述过程连接上来重复下载，才推断大概率是pcdn刷流量。
猜测的吸血逻辑就是：选取一些热门种子，这些种子做种用户多于是就选一小部分用户吸血，吸到一个不超过种子大小的量后又换另一批用户。如此循环，数量能跑满带宽就行，还能汇报进度。感觉这种吸血方式有够阴险的

**Comment by Simple-Tracker** [comment]
感谢反馈!

已通过更新 config.json 解决此问题.
