### ISSUE TITLE
可疑的客户端类型 Transmission 2.9x

### ISSUE THREAD

**Issue by chesha1** [Simple-Tracker/qBittorrent-ClientBlocker#81]
最近遇到好多客户端类型 Transmission 2.9x 的，如果大规模地使用一个老旧（至少都是 6 年前的了）的客户端，并且占用了很高的上传速度，感觉不太正常

以下是部分观察到的 ip 和 客户端：

- 121.33.115.187 Transmission 2.93
- 116.23.126.147 Transmission 2.93
- 60.255.229.225 Transmission 2.94
- 183.195.18.144 Transmission 2.92
- 120.79.165.182 Transmission 2.94

看过去的 issue，也提到 Transmission 2.94，建议把 Transmission 2.9x 的客户端都禁了

**Comment by Simple-Tracker** [comment]
感谢反馈!

但我在想, 更换客户端名称似乎对攻击者也毫无成本, 但有可能这些是动态 IP?

**Comment by chesha1** [comment]
最好加入检测进度功能，看看各个用户有没有虚假汇报的，有的话上报这个 IP

然后做一个云端的配置中心定时拉取新的屏蔽规则，因为 IP 资源不是无限的，慢慢来总能把所有可疑 IP 都屏蔽了

关于云端的配置中心，可以试试 GitHub/Cloudflare Pages？先用有大量免费额度的 serverless 服务，而且这两个也没被墙，Cloudflare Worker 和 Vercel 全系列被墙了

**Comment by Mapaler** [comment]
> 最近遇到好多客户端类型 Transmission 2.9x 的，如果大规模地使用一个老旧（至少都是 6 年前的了）的客户端，并且占用了很高的上传速度，感觉不太正常
 
我的路由器是10年前的 Linksys 洋垃圾，买的别人的 OpenWrt，上面就是 Transmission 2.9.4，自己不会编译，想换3也换不了。

比如这个个PT也建议用2+而不是3
![firefox_e1uTjrwdKR](https://github.com/user-attachments/assets/4672e78d-0a2e-42e9-a50f-24eb24ac45a0)

**Comment by chesha1** [comment]
@Mapaler 感谢提醒，是我误会的，看来是有大量正常用户在用 Transmission 2.9x

**Comment by Simple-Tracker** [comment]
3.4p3 通过默认订阅外部封禁 IP 列表解决了问题. 但用户需要有良好的网络以获取订阅列表.

**Comment by Simple-Tracker** [comment]
> > 3.4p3 通过默认订阅外部封禁 IP 列表解决了问题. 但用户需要有良好的网络以获取订阅列表.
> 
> 这一功能需要在设置中额外开启吗？还是默认行为
> 
> 如果因为网络原因访问不了 `all.txt`，终端中会有提示吗？
> 
> 源文件位于 Github，很多中国大陆的用户可能需要一个代理才能访问这个文件，能否在 config 中加入设置代理的选项，不然直连不一定能下载到
> 
> 问题有点多，感谢您的开发

1. 默认行为;
2. 会有提示;
3. 未来会引入自动检测/自动设置代理;
