### ISSUE TITLE
好像已经有李鬼客户端来吸血了？

### ISSUE THREAD

**Issue by Xibeilius** [Simple-Tracker/qBittorrent-ClientBlocker#82]
qB的4.6.5没更新几天，然后今早出来个这么个玩意吸了我55G，客户端名字是qBittorent/4.6.5，好像正常客户端中间没反斜杠吧，屏蔽器也没拦住。我也不是太懂，这种情况应该不正常吧？
![Uploading 屏幕截图 2024-06-22 092650.png…]()

**Comment by Xibeilius** [comment]
![屏幕截图 2024-06-22 092650](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/131810906/2eb5e890-ec99-4a52-a3f3-56862cdaabcf)

**Comment by Xibeilius** [comment]
顺便，这个人把一个600M左右的文件下了不知道多少遍，怎么想也不正常。

**Comment by Simple-Tracker** [comment]
感谢反馈!

看起来这是一个新的需要屏蔽的 IP 段, 已更新 config.json 以解决此问题.

**Comment by Xibeilius** [comment]
> 感谢反馈!
> 
> 看起来这是一个新的需要屏蔽的 IP 段, 已更新 config.json 以解决此问题.

这个IP段真的狡猾，会把自己伪装成qBittorrent/4.6.5和qBittorrent/4.6.3，是不是从客户端名字上不太好下手啊？

**Comment by Simple-Tracker** [comment]
是的, 客户端名称目前参考价值并不大.

**Comment by tanmoumou252** [comment]
今天刚遇到,而且他们经常会突破客户端的限速,不知道怎么做到的,我都限制2MB/s了但是上传会跑到7MB/s
![Aobs录屏06-27_11-17-17 mp4_20240627_111918 963](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/118299342/62d72405-d94c-483a-9b6f-7da1149f2433)

**Comment by SaharaMiyoko** [comment]
> ![屏幕截图 2024-06-22 092650](https://private-user-images.githubusercontent.com/131810906/341918394-2eb5e890-ec99-4a52-a3f3-56862cdaabcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNzI3MDUsIm5iZiI6MTcyMDE3MjQwNSwicGF0aCI6Ii8xMzE4MTA5MDYvMzQxOTE4Mzk0LTJlYjVlODkwLWVjOTktNGE1Mi1hM2YzLTU2ODYyY2RhYWJjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQwOTQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2UwNzllY2IwZjc5NDIxODE5MDYzMzgzMjQ4Zjg1OThjZDJiMTc5MzNmYjkxMWJmOTRkMTdhMThkOTMyN2E2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z9F0pJQ37-j4uCnKj-trpaAh5wLNAV236-A7RelcmYs)

没有开斜杠的是开了匿名模式
https://www.cometbbs.com/t/208%E6%B5%8B%E8%AF%95%E7%89%88/92328/77

**Comment by Simple-Tracker** [comment]
由于已在 IP 屏蔽列表, 关闭此问题!
