### ISSUE TITLE
XL0012依然没有被完全屏蔽

### ISSUE THREAD

**Issue by FanxJK** [Simple-Tracker/qBittorrent-ClientBlocker#84]
![image](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/22773968/d8e21c71-ed82-4c2b-81cd-469360b644b8)

问题依旧存在，使用 [3.4b2](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/releases/tag/3.4b2)版本
docker 环境变量方式启动

![image](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/22773968/c2660d33-651c-4fe1-af5d-753a0154e263)
![image](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/22773968/776bc87c-ea41-437b-a6e1-4144998eba81)

**Comment by FanxJK** [comment]
![image](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/22773968/78b32aac-0fe3-460a-a352-0d4523421553)

**Comment by Simple-Tracker** [comment]
感谢反馈!

目前需要手动更新 config.json, 将发布新版本解决此问题.
