### ISSUE TITLE
建议屏蔽XL0019，最起码至少提供到可选列表里

### ISSUE THREAD

**Issue by SaharaMiyoko** [Simple-Tracker/qBittorrent-ClientBlocker#90]
可能是最近-dt,-hp,-xm这些🐂🐎客户端太多了让迅雷看上去简直都是神仙了，但是，我觉得这并不是不屏蔽迅雷的原因，理由有下
1、如果不屏蔽XL0019，那么μtorrent web、dandanplay也不应该提供到可选屏蔽列表里，因为性质都是一样的，**只是在下载阶段提供上传**
2、虽然新版迅雷在下载阶段会上传，实际上可能提供的上传所剩无几，因为中国宽带的特性：上下行严重不对等、绝大多数人没有公网IP、ipv6普及率低，而绝大多数使用迅雷的用户**根本不知道更不会去考虑这些东西**
3、新迅雷虽然现在提供了上传，但是**只是在下载阶段上传**，而不是**下载完后的做种**，保持bt网络充满活力的是那些正在下载的客户端还是下载完做种的客户端?**做种，才是保持bt稳定的重要因素**
4、dt、hp等客户端是毒瘤，并不意味着xunlei就不是毒瘤。迅雷这次搞在下载阶段上传，**本质上是为了维持它的垄断地位**。因为它想**通过这种方式欺骗bt社区，以便于它继续吸血**。会做种的迅雷永远不会出现，因为**这与迅雷的根本利益相违背**，对于企业或是资本来说，利益永远是第一位，迅雷不可能白白将自己手里的东西給别人。**只要迅雷存在一天，它的垄断地位就存在一天，国内的bt环境就糟糕一天**
综上，我希望对迅雷采取一刀切的手段，只有迅雷用户少了更多人才会转向正规客户端，真正理解bt网络的运行原理，才能真正的保持bt网络的可持续
附：
![屏幕截图 2024-07-05 171511](https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/assets/104242390/9f341188-9c8f-4d6e-91ee-0256182bdee7)
（只是个人观点，希望能被采纳）

**Comment by SaharaMiyoko** [comment]
> 可能是最近-dt,-hp,-xm这些🐂🐎客户端太多了让迅雷看上去简直都是神仙了，但是，我觉得这并不是不屏蔽迅雷的原因，理由有下 1、如果不屏蔽XL0019，那么μtorrent web、dandanplay也不应该提供到可选屏蔽列表里，因为性质都是一样的，**只是在下载阶段提供上传** 2、虽然新版迅雷在下载阶段会上传，实际上可能提供的上传所剩无几，因为中国宽带的特性：上下行严重不对等、绝大多数人没有公网IP、ipv6普及率低，而绝大多数使用迅雷的用户**根本不知道更不会去考虑这些东西** 3、新迅雷虽然现在提供了上传，但是**只是在下载阶段上传**，而不是**下载完后的做种**，保持bt网络充满活力的是那些正在下载的客户端还是下载完做种的客户端?**做种，才是保持bt稳定的重要因素** 4、dt、hp等客户端是毒瘤，并不意味着xunlei就不是毒瘤。迅雷这次搞在下载阶段上传，**本质上是为了维持它的垄断地位**。因为它想**通过这种方式欺骗bt社区，以便于它继续吸血**。会做种的迅雷永远不会出现，因为**这与迅雷的根本利益相违背**，对于企业或是资本来说，利益永远是第一位，迅雷不可能白白将自己手里的东西給别人。**只要迅雷存在一天，它的垄断地位就存在一天，国内的bt环境就糟糕一天** 综上，我希望对迅雷采取一刀切的手段，只有迅雷用户少了更多人才会转向正规客户端，真正理解bt网络的运行原理，才能真正的保持bt网络的可持续 附： ![屏幕截图 2024-07-05 171511](https://private-user-images.githubusercontent.com/104242390/346077821-9f341188-9c8f-4d6e-91ee-0256182bdee7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNzE5NjksIm5iZiI6MTcyMDE3MTY2OSwicGF0aCI6Ii8xMDQyNDIzOTAvMzQ2MDc3ODIxLTlmMzQxMTg4LTljOGYtNGQ2ZS05MWVlLTAyNTYxODJiZGVlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQwOTI3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGY2YzYzYWVhZjM4YTBmZmJlYmYyZGE5YzdhYjIzYTQ3NjBjZjVmMTgyMTdmOWRlMzBjMGM5MzQ1MzU4OTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NM9SZ1ZPxuk8PWFD8Vj6kbw8joUMQaI0dLayE5npQec) （只是个人观点，希望能被采纳）

https://hub.yzuu.cf/c0re100/qBittorrent-Enhanced-Edition/issues/5

**Comment by Simple-Tracker** [comment]
感谢反馈!

已加入可选列表.

**Comment by SaharaMiyoko** [comment]
> 感谢反馈!
> 
> 已加入可选列表, 但我的观点是: 若迅雷这种用户体量的客户端有良性行为, 那么 **理论上** 它对 BT 生态是正面的, 特别是在大量老版本迅雷升级新版本后, 尽管实际上用户习惯使这个效果影响了很多.

理解你的意思，但是我还是保留观点，对于这样子的公司就是应该采取彻底的抵制，因为这种行为的本质就是**把免费的东西私有化**，就如同英国的**圈地运动**一样，除非迅雷会做种，但那是**永远不可能的**，这与他们的利益相违

**Comment by n-ine** [comment]
想一刀切的话只需要把（?!19）删掉就可以了
不过我希望对xfplay和xl0019升级策略 即下载的过程中允许连接 做种的时候禁止连接 对等的去进行黑名单/白名单

**Comment by Simple-Tracker** [comment]
根据相关来源: https://github.com/PBH-BTN/PeerBanHelper/issues/254
由于 -XL0019- 的比例实在是低的离谱, 用户原因不太能解释 0.0004 的分享率, 由此它对社区弊大于利, 故已重新加回屏蔽列表.

**Comment by Simple-Tracker** [comment]
3.4p5 已重新默认屏蔽 -XL0019-.
