### ISSUE TITLE
疑似新的伪装客户端

### ISSUE THREAD

**Issue by LMDM387** [Simple-Tracker/qBittorrent-ClientBlocker#91]
这种名称几乎可以确认是吸血的玩意了：
GT003（客户端标识：offline-download）
IP：59.47.225.204
![QQ截图20240712210751](https://github.com/user-attachments/assets/ff0976dc-4f7b-4a6f-9bd4-59b80dd21e21)

**Comment by LMDM387** [comment]
更新到最新版本后看到GT002的Peer已经ban了，我先手动改一下config屏蔽

**Comment by Simple-Tracker** [comment]
感谢反馈!

由于 offline-download 已位于屏蔽列表, 它应当能被妥善的自动屏蔽.
