### ISSUE TITLE
希望支持代理来连接到github

### ISSUE THREAD

**Issue by mzhboy** [Simple-Tracker/qBittorrent-ClientBlocker#94]
众所周知瓷器国到github的连接受到干扰。
我目前使用systemd启动qbc，理所当然地直连github失败了。
希望能够支持socks5代理工具，通过代理工具访问github

**Comment by mzhboy** [comment]
对了，现在暂且可以用反代站访问github，需要简单修改url。

**Comment by IAALAI** [comment]
已经有类似的计划了，回头下一代的话，会尝试使用CF反代github中的内容来提升使用体验。至于代理的话，个人感觉确实有意义，因为很大概率调用 client 和 获取更新 分别是在内网和公网，如果在qbcb内部添加一个代理使用功能确实可能会提供一些方便。但是讲话的，你的代理工具不会不能设置绕过局域网已经大陆吧。。。还是说你的 client 也在公网之中？虽然增加代理确实有意义，但是这个任务的优先级很低。。。但是将内部的URL换掉已经在做了

**Comment by IAALAI** [comment]
已经有类似的计划了，回头下一代的话，会尝试使用CF反代github中的内容来提升使用体验。至于代理的话，个人感觉确实有意义，因为很大概率调用 client 和 获取更新 分别是在内网和公网，如果在qbcb内部添加一个代理使用功能确实可能会提供一些方便。但是讲话的，你的代理工具不会不能设置绕过局域网已经大陆吧。。。还是说你的 client 也在公网之中？虽然增加代理确实有意义，但是这个任务的优先级很低。。。但是将内部的URL换掉已经在做了

**Comment by Simple-Tracker** [comment]
感谢反馈!

3.4p6 起支持自动检测并(对所有网络请求)使用代理, 但要求代理具备正确的分流策略, 以避免无法访问客户端的问题.

**Comment by mzhboy** [comment]
目前还没用 `HTTP_PROXY ` 这样来设置代理，因为不太方便。我是linux客户端，如果能够自动给github之类的域名添加反代也行。但是显示支持socks代理会更好，这样仅github使用代理。

**Comment by Simple-Tracker** [comment]
SOCKS 相对实现繁琐一些, 一个简单的方案是: 在启动时附加环境变量. 若是通过服务, 也可在服务配置文件本身做处理.

如: ```HTTP_PROXY="http://127.0.0.1:8080" HTTPS_PROXY="http://127.0.0.1:8080" ./qBittorrent-ClientBlocker```
